# Generated by Django 6.0.3 on 2026-03-21 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('pantry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='user_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='pantry.userproduct'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['trigger_date', 'sent'], name='alerts_trigger_109cb8_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['user', 'sent', 'dismissed'], name='alerts_user_id_49875d_idx'),
        ),
    ]
