# Generated by Django 6.0.3 on 2026-03-21 16:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('barcode', 'Barcode'), ('ticket', 'Ticket'), ('manual', 'Manual')], max_length=20)),
                ('products_count', models.PositiveSmallIntegerField(default=0)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scan_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_override', models.CharField(blank=True, max_length=255)),
                ('add_method', models.CharField(choices=[('barcode', 'Barcode'), ('ticket', 'Ticket'), ('manual', 'Manual')], max_length=20)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('expiry_estimated', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('consumed', 'Consumed'), ('expired', 'Expired'), ('removed', 'Removed')], default='active', max_length=20)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('catalog_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_instances', to='catalog.productcatalog')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='pantry.scansession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_products',
                'ordering': ['expiry_date', 'created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='user_produc_user_id_84571c_idx'), models.Index(fields=['user', 'expiry_date'], name='user_produc_user_id_399a79_idx')],
            },
        ),
    ]
