# Generated by Django — storage + units_in_pack

from django.db import migrations, models

DRY = frozenset(
    {
        "cereals",
        "canned",
        "snacks",
        "condiments",
        "beverages",
        "bakery",
    }
)


def forwards_storage(apps, schema_editor):
    UserProduct = apps.get_model("pantry", "UserProduct")
    ProductCatalog = apps.get_model("catalog", "ProductCatalog")
    for up in UserProduct.objects.all().iterator():
        if up.is_frozen:
            up.storage = "freezer"
        else:
            cat = None
            if up.catalog_product_id:
                row = (
                    ProductCatalog.objects.filter(pk=up.catalog_product_id)
                    .values("category")
                    .first()
                )
                if row:
                    cat = row["category"]
            if not cat and up.manual_category:
                cat = up.manual_category
            if cat in DRY:
                up.storage = "pantry"
            else:
                up.storage = "fridge"
        up.save(update_fields=["storage"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("pantry", "0003_userproduct_manual_category_frozen"),
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userproduct",
            name="storage",
            field=models.CharField(
                choices=[
                    ("pantry", "Pantry"),
                    ("fridge", "Fridge"),
                    ("freezer", "Freezer"),
                ],
                default="fridge",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userproduct",
            name="units_in_pack",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(forwards_storage, noop_reverse),
    ]
