# Generated by Django 6.0.3 on 2026-04-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0004_userproduct_storage_units_in_pack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproduct',
            name='storage',
            field=models.CharField(choices=[('pantry', 'Pantry'), ('fridge', 'Fridge'), ('freezer', 'Freezer')], default='fridge', help_text='User-facing location; is_frozen is kept in sync on save.', max_length=20),
        ),
        migrations.AlterField(
            model_name='userproduct',
            name='units_in_pack',
            field=models.PositiveSmallIntegerField(blank=True, help_text='When set, quantity is units remaining in a multipack (1..units_in_pack).', null=True),
        ),
    ]
