# Generated by Django 6.0.3 on 2026-04-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0005_alter_userproduct_storage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproduct',
            name='units_in_pack',
            field=models.PositiveSmallIntegerField(blank=True, help_text='When set, pieces per retail pack (e.g. 3); quantity is total pieces on the line, not limited by this.', null=True),
        ),
    ]
