# Generated by Django 6.0.3 on 2026-03-21 16:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barcode', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('dairy', 'Dairy'), ('fruits', 'Fruits'), ('vegetables', 'Vegetables'), ('meat', 'Meat'), ('fish', 'Fish'), ('beverages', 'Beverages'), ('snacks', 'Snacks'), ('cereals', 'Cereals'), ('frozen', 'Frozen'), ('condiments', 'Condiments'), ('bakery', 'Bakery'), ('canned', 'Canned'), ('other', 'Other')], default='other', max_length=20)),
                ('image_url', models.URLField(blank=True)),
                ('nutri_score', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('nova_group', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('calories', models.FloatField(blank=True, null=True)),
                ('proteins', models.FloatField(blank=True, null=True)),
                ('carbs', models.FloatField(blank=True, null=True)),
                ('fats', models.FloatField(blank=True, null=True)),
                ('sugars', models.FloatField(blank=True, null=True)),
                ('shelf_life_days', models.PositiveIntegerField(blank=True, null=True)),
                ('off_id', models.CharField(blank=True, max_length=100)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_catalog',
                'indexes': [models.Index(fields=['barcode'], name='product_cat_barcode_b30f2f_idx'), models.Index(fields=['name'], name='product_cat_name_674033_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_name', models.CharField(db_index=True, max_length=255)),
                ('confidence', models.FloatField(default=1.0)),
                ('source', models.CharField(choices=[('ai', 'AI'), ('user', 'User'), ('barcode', 'Barcode')], default='ai', max_length=20)),
                ('confirmed_count', models.PositiveIntegerField(default=0)),
                ('catalog_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='catalog.productcatalog')),
            ],
            options={
                'db_table': 'product_matches',
                'indexes': [models.Index(fields=['raw_name'], name='product_mat_raw_nam_5f4c7a_idx'), models.Index(fields=['-confirmed_count'], name='product_mat_confirm_913234_idx')],
                'unique_together': {('raw_name', 'catalog_product')},
            },
        ),
    ]
