# Generated by Django 6.0.3 on 2026-03-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productcatalog',
            index=models.Index(fields=['off_id'], name='product_cat_off_id_01f02a_idx'),
        ),
    ]
