# Generated by Django 6.0.3 on 2026-03-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productcatalog_product_cat_off_id_01f02a_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productcatalog',
            name='product_cat_name_674033_idx',
        ),
        migrations.RenameField(
            model_name='productcatalog',
            old_name='brand',
            new_name='brands',
        ),
        migrations.AddField(
            model_name='productcatalog',
            name='name_de',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productcatalog',
            name='name_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productcatalog',
            name='name_es',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productcatalog',
            name='name_fr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productcatalog',
            name='name_it',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productcatalog',
            name='name_pt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='productcatalog',
            name='off_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='productcatalog',
            name='name',
        ),
    ]
