# Generated by Django 6.0.3 on 2026-03-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_productcatalog_product_cat_name_674033_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcatalog',
            name='is_organic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productcatalog',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
